### ISSUE TITLE
[feat] User Property 트래킹 코드 심기

### ISSUE THREAD

**Issue by t1nm1ksun** [TeamDATEROAD/DATEROAD-ANDROID#268]
## What is this issue? 🛠
- User Property 트래킹 코드 심기 

## Progress 🏃‍♀️
- [x] user_name
- [x] user_point
- [x] user_free_remained
- [x] user_purchase_count
- [x] user_course_count
- [x] date_schedule_num

**Comment by Felipe-Rafael-Rosa** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)
